export const AUTH_FAILED_ERROR_TYPE = "AUTH_FAILED";
export const CONTENT_TYPE_NOT_VALID_ERROR_TYPE =
  "CONTENT_TYPE_NOT_VALID_ERROR_TYPE";
export const DESTINATION_NOT_VALID_ERROR_TYPE = "DESTINATION_NOT_VALID";
export const OBJECT_NOT_FOUND_ERROR_TYPE = "OBJECT_NOT_FOUND";
export const REQUEST_FAILED_ERROR_TYPE = "REQUEST_FAILED";
export const RE_SENDING_NOT_ALLOWED_ERROR_TYPE = "RE_SENDING_NOT_ALLOWED";
export const SMS_TEMPLATE_NOT_VALID_ERROR_TYPE = "SMS_TEMPLATE_NOT_VALID";
